name: prosa_hi_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+3

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_riverpod: ^3.0.3
    intl: 0.20.2
    permission_handler: ^12.0.0+1
    async: ^2.13.0
    path_provider: ^2.1.5
    flutter_launcher_icons: ^0.14.4
    hive_ce: ^2.15.1
    hive_ce_flutter: ^2.3.4
    collection: ^1.18.0
    dio: ^5.8.0+1
    flutter_dotenv: ^6.0.0
    equatable: ^2.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    hive_ce_generator: ^1.9.3
    build_runner: ^2.4.11

flutter_launcher_icons:
    android: 'launcher_icon'
    ios: false
    image_path: 'assets/images/app-icon.png'
    min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
    generate: true
    uses-material-design: true
    assets:
        - .env.stage
        - .env.prod
        - assets/icons/
        - assets/images/
        - assets/json_data/

    fonts:
        - family: PlusJakartaSans
          fonts:
              - asset: assets/fonts/PlusJakartaSans-Bold.ttf
                weight: 700
              - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/PlusJakartaSans-Medium.ttf
                weight: 500
              - asset: assets/fonts/PlusJakartaSans-Regular.ttf
                weight: 400
